version: '3.8'
services:
db:
image: postgres:16
environment:
POSTGRES_USER: mysats
POSTGRES_PASSWORD: mysats123
POSTGRES_DB: mysats_dev
ports:
- '5432:5432'
volumes:
- db_data:/var/lib/postgresql/data

api:
build: ./api
ports:
- '8080:8080'
environment:
SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mysats_dev
SPRING_DATASOURCE_USERNAME: mysats
SPRING_DATASOURCE_PASSWORD: mysats123
depends_on:
- db

mailhog:
image: mailhog/mailhog
ports:
- '1025:1025'
- '8025:8025'

volumes:
db_data:
